Vector async slicing nap
andy-sweet/napari pull request #18
Opened 2022-06-27 19:26 UTC by kcpevey

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2022-06-27 20:37 UTC, andy-sweet requested changes
Looks great - I just had some minor suggestions around formatting.

Also, you should also add yourself as an author to the doc at the top. Email is optional.

2022-06-27 20:37 UTC, andy-sweet commented on docs/naps/4-async-slicing.md
> +        indices of the _mesh_vertices that form the faces of the M in view vectors.
```suggestion
        indices of the `_mesh_vertices` that form the faces of the M in view vectors.
```

2022-06-27 20:37 UTC, andy-sweet commented on docs/naps/4-async-slicing.md
> +	- Note: `_view_faces` and `view_vertices` require:
```suggestion
	- Note: `_view_faces` and `_view_vertices` require:
```

2022-06-27 20:37 UTC, andy-sweet commented on docs/naps/4-async-slicing.md
> +	- `out_of_slice_display`: `bool`:
```suggestion
    - `out_of_slice_display`: `bool`:
```

2022-06-27 20:37 UTC, andy-sweet commented on docs/naps/4-async-slicing.md
> +## Related Technical Details
Love these details. Happy to merge them for now. We can think about the best place for them later this week.

2022-06-29 15:16 UTC, kcpevey commented
Thanks @andy-sweet! I've made the requested changes. This is ready for review again.

2022-06-29 15:57 UTC, andy-sweet approved these changes
Looks great, will merge this now!

2022-06-29 15:58 UTC, merged