Async slicing vector layer
andy-sweet/napari pull request #19
Opened 2022-06-29 20:12 UTC by kcpevey

# Description

## Type of change

- [ ] Bug-fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# References

# How has this been tested?

- [ ] example: the test suite for my feature covers cases x, y, and z
- [ ] example: all tests pass with my change
- [ ] example: I check if my changes works with both PySide and PyQt backends
      as there are small differences between the two Qt bindings.  

## Final checklist:
- [ ] My PR is the minimum possible work for the desired functionality
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] If I included new strings, I have used `trans.` to make them localizable.
      For more information see our [translations guide](https://napari.org/docs/dev/guides/translations.html).

2022-07-06 23:01 UTC, andy-sweet requested changes
This looks good to me to merge after deleting some commented code. Ideally, I'd like to see complete removal of `self` from slicing (i.e. make `_get_slice` a static method), but I didn't do that in my initial PR and you don't need to do it here.

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        # self._mesh_triangles = triangles
```suggestion
```

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        # self._mesh_triangles = triangles
```suggestion
```

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        # self._mesh_triangles = triangles
```suggestion
```

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        # self._mesh_triangles = triangles
```suggestion
```

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +            # TODO I don't understand this
I think the 0 means that we use the start points of the vectors to determine which vectors are in this slice.

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +                # TODO I don't understand this - why 0.5?
In the regular case (i.e. no out of slice display / thick slices), then the thickness of a slice is 1 (in the "data" coordinate system).

E.g. when taking a 2D slice of 3D data you can think of 2D plane (with no thickness). You could also add some thickness to that plane to create a slab. In the regular case we add 0.5 on either side for a thickness of 1. The distances are the distances from the vector start points to that plane, so any distances < 0.5 represents points in that slab of thickness 1.

Does that make more sense?

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        self._update_mesh()  # sledgehammer to avoid more delicate implementation...
No need to fix in this PR, but is likely something we'd need to fix in the future. The intent is that `_make_slice_request` should execute on the main thread, so it should be fast and do limited ops (i.e. mostly just building the request and maybe making some protective copies when needed).

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        # TODO: what is this?
Looks like this is for handling 2D vertices being displayed in 3D. This will pad them to be 3D by adding a column of zeros. Unsure if this is really needed (for images it was not even though there was some code for it).

2022-07-06 23:01 UTC, andy-sweet commented on napari/_vispy/layers/vectors.py
> +        # this logic has been moved to the get_slice layer class
In my opinion, these are more like special behaviors of vispy (e.g. it often can't handle empty data), so I might leave them here. But I don't feel strongly.

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +        # self._mesh_triangles = triangles
This looks like a simple refactor that you could do on `main` right now, and one which I'd encourage.

2022-07-06 23:01 UTC, andy-sweet commented on napari/layers/vectors/vectors.py
> +    def _view_face_color(self, view_indices, view_alphas, ndisplay, ndim, edge_color) -> np.ndarray:
Looks like `self` isn't used, so make this a `staticmethod`? That makes it clear that `self` isn't involved.

2022-07-06 23:13 UTC, andy-sweet commented
Also, if you want me to merge this (and you should), then mark this as ready for review instead of draft.

2022-07-07 15:39 UTC, kcpevey commented on napari/layers/vectors/vectors.py
> +        # self._mesh_triangles = triangles
One thing I noticed is that when I moved these into a separate function called `_update_mesh()`, that I needed some additional triggers for it. I was a little confused. I can apply this on main and then it may be more clear (and also it may just work...).

2022-07-07 15:41 UTC, kcpevey commented on napari/layers/vectors/vectors.py
> +    def _view_face_color(self, view_indices, view_alphas, ndisplay, ndim, edge_color) -> np.ndarray:
ah yes, good point

2022-07-07 15:42 UTC, kcpevey commented on napari/layers/vectors/vectors.py
> +            # TODO I don't understand this
oh ok. thanks!

2022-07-07 15:42 UTC, kcpevey commented on napari/layers/vectors/vectors.py
> +                # TODO I don't understand this - why 0.5?
yes, thanks.

2022-07-07 15:46 UTC, kcpevey commented on napari/layers/vectors/vectors.py
> +        self._update_mesh()  # sledgehammer to avoid more delicate implementation...
yeah, this call to `_update_mesh` really shouldn't be here. Instead there should be a separate trigger or set of triggers which call `_update_mesh` after certain changes. Then the call to it here can be removed.

2022-07-07 15:47 UTC, kcpevey commented on napari/layers/vectors/vectors.py
> +        # TODO: what is this?
got it. I guess the usecase may be that you have another layer which _is_ 3D and you have a 2D vector layers turned on as well?

2022-07-07 15:48 UTC, kcpevey commented on napari/_vispy/layers/vectors.py
> +        # this logic has been moved to the get_slice layer class
well there was already an empty data check over on `set_view_slice` so I just combined them...

2022-07-07 15:50 UTC, kcpevey commented
Re: commented code. Yes, I should have mentioned that. I left my comments in since I still had questions and also needed my notes to myself :) Now that you're ready to move forward, I'll get those cleanup up!

2022-07-19 20:33 UTC, andy-sweet approved these changes
Looks good to me now. I'm going to merge this in and mark the corresponding task as done.

2022-07-19 20:33 UTC, merged